completed css-positioning
louiewhitz/c0522-code-solutions pull request #17
Opened 2022-05-13 18:25 UTC by louiewhitz

![Screen Shot 2022-05-13 at 10 44 47 AM](https://user-images.githubusercontent.com/99847558/168343270-a862941a-1a76-4f00-a3cc-6f84e4361edf.png)
<img width="919" alt="Screen Shot 2022-05-13 at 11 01 44 AM" src="https://user-images.githubusercontent.com/9
<img width="678" alt="Screen Shot 2022-05-13 at 11 25 05 AM" src="https://user-images.githubusercontent.com/99847558/168344607-b420b657-5af1-4ce0-a8c2-76de089a65c3.png">
9847558/168343282-66b06827-f3ac-476d-af96-3eb6a085ca9c.png">

2022-05-13 18:45 UTC, louiewhitz commented
<img width="919" alt="Screen Shot 2022-05-13 at 11 01 44 AM" src="https://user-images.githubusercontent.com/99847558/168347405-14349c2f-faf9-4b3d-92e6-a6e8941cf1a1.png">

2022-05-14 23:26 UTC, codingcodymiller requested changes

2022-05-14 23:26 UTC, codingcodymiller commented on css-positioning/fixed.css
> +  left: 100px;
If you make the title `width: 100%`, this won't be necessary, since `text-align: center;` has already been applied

2022-05-15 19:53 UTC, codingcodymiller approved these changes

2022-06-12 03:34 UTC, merged