CSS two column layout.
louiewhitz/c0522-code-solutions pull request #19
Opened 2022-05-15 06:08 UTC by louiewhitz

![Screen Shot 2022-05-14 at 9 52 42 PM](https://user-images.githubusercontent.com/99847558/168459604-6c2f46e9-8a6f-463e-a63c-158a59d2252a.png)

2022-05-15 19:45 UTC, codingcodymiller requested changes
Hey Louisa, your output doesn't match the example output in multiple ways. For instance, your fonts are incorrect in multiple places, and your content is not vertically aligned in the right set of columns. Please revise and submit a new screenshot with your revision. 

![image](https://user-images.githubusercontent.com/32880187/168491064-d512d0af-80b6-4f30-a421-11f646aef3ea.png)

2022-05-23 01:30 UTC, louiewhitz commented
![Screen Shot 2022-05-22 at 6 05 50 PM](https://user-images.githubusercontent.com/99847558/169726835-a4270a43-de1f-4048-be12-bf2dc2da010d.png)

2022-05-23 15:59 UTC, codingcodymiller requested changes
Hey Louisa, this isn't making use of proper layout classes. I see you have a `container` class, but you don't have a `row` or any `column` classes. Please revise this to make use of proper layout classes.

2022-05-28 03:07 UTC, louiewhitz reviewed
<img width="1028" alt="Screen Shot 2022-05-27 at 8 05 25 PM" src="https://user-images.githubusercontent.com/99847558/170807507-4f1cfd22-3f9e-47ce-b7d9-f723129656ae.png">

2022-05-30 17:05 UTC, codingcodymiller requested changes

2022-05-30 17:05 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +        <div class="info-card-image-column">
`column` classes should be named after their size, not their content. Make sure you address this on any other `column` classes in this document as well.

2022-06-21 17:58 UTC, codingcodymiller approved these changes

2022-06-21 23:25 UTC, merged