JavaScript Data Models
louiewhitz/c0522-code-solutions pull request #24
Opened 2022-05-17 19:04 UTC by louiewhitz

![Screen Shot 2022-05-17 at 11 22 12 AM](https://user-images.githubusercontent.com/99847558/168890641-5d36c055-1d2c-44ad-a523-78548e9c196c.png)

2022-05-17 19:29 UTC, codingcodymiller requested changes
Hey Louisa! There is **_a lot_** more data in the screenshot that you haven't accounted for yet. Make sure you are creating a structure that will provide all the data necessary to create that output image

2022-05-17 22:43 UTC, codingcodymiller requested changes
In addition to my other comments, there is still a significant amount of data you are not accounting for, especially about the order itself.

2022-05-17 22:43 UTC, codingcodymiller commented on javascript-data-model/order-history.js
> +  }]]
This array is not being stored in a property 🤔

2022-05-17 22:43 UTC, codingcodymiller commented on javascript-data-model/order-history.js
> +  }]]
Were you getting an error when you wrote this in your code editor? Make sure you pay attention to yellow and red squiggly lines, they are there for a reason.

2022-05-18 17:54 UTC, codingcodymiller requested changes

2022-05-18 17:54 UTC, codingcodymiller commented on javascript-data-model/order-history.js
> +}
This syntax is super wrong, if you opened this in the browser, you likely have parsing errors in your console.

2022-05-20 03:38 UTC, louiewhitz commented
![Screen Shot 2022-05-19 at 8 27 55 PM](https://user-images.githubusercontent.com/99847558/169445742-9739cd5a-df12-4d98-8c74-6953f57d9179.png)

2022-05-20 17:39 UTC, codingcodymiller requested changes

2022-05-20 17:39 UTC, codingcodymiller commented on javascript-data-model/order-history.js
> +}];
This looks like two separate orders right now, you want one order object for each order which will hold an array of all items in that order.

2022-05-23 01:39 UTC, louiewhitz commented
![Screen Shot 2022-05-22 at 6 36 19 PM](https://user-images.githubusercontent.com/99847558/169727465-81b5706f-476e-47bb-815a-846c44548dc5.png)

2022-05-23 16:05 UTC, codingcodymiller approved these changes

2022-06-12 03:33 UTC, merged