JS Functions
louiewhitz/c0522-code-solutions pull request #25
Opened 2022-05-18 02:52 UTC by louiewhitz

<img width="1307" alt="Screen Shot 2022-05-17 at 7 49 53 PM" src="https://user-images.githubusercontent.com/99847558/168947391-be46c469-13c6-4978-b2fc-cf9d891f66a3.png">

2022-05-18 17:58 UTC, codingcodymiller requested changes

2022-05-18 17:58 UTC, codingcodymiller commented on javascript-functions/main.js
> +  console.log(greeting);
You should be `return`ing the final greeting value, not logging it in the function.

2022-05-20 02:51 UTC, louiewhitz reviewed
![Screen Shot 2022-05-19 at 7 42 00 PM](https://user-images.githubusercontent.com/99847558/169439195-e75515ae-34ed-4d3a-bae5-85a79808a7dc.png)

2022-05-20 17:39 UTC, codingcodymiller approved these changes

2022-06-12 03:33 UTC, merged