Javascript Loops
louiewhitz/c0522-code-solutions pull request #26
Opened 2022-05-19 21:27 UTC by louiewhitz

![Screen Shot 2022-05-19 at 2 26 46 PM](https://user-images.githubusercontent.com/99847558/169407464-b5027f2f-8999-409a-a48f-64ac887d06bc.png)
![Screen Shot 2022-05-19 at 2 26 38 PM](https://user-images.githubusercontent.com/99847558/169407475-17ef437c-bf90-4738-8c4f-985828772659.png)

2022-05-20 17:33 UTC, codingcodymiller requested changes

2022-05-20 17:33 UTC, codingcodymiller commented on javascript-loops/main.js
> +var currentNumbers = 1;
You should not be making variables for use in a function outside of the function definition, that means these variables will continue to exist longer than they need to, which is not ideal. If you only intend to use a variable inside of a single function, that variable should be declared inside the function. Make sure you address this in your other function definitions as well.

2022-05-23 16:08 UTC, codingcodymiller requested changes

2022-05-23 16:08 UTC, codingcodymiller commented on javascript-loops/main.js
> +var currentNumber = 2;
My comment in my previous review applies here.

2022-05-23 16:08 UTC, codingcodymiller commented on javascript-loops/main.js
> +var keys = [];
My comment in my previous review applies here.

2022-05-28 03:15 UTC, louiewhitz commented
![Screen Shot 2022-05-27 at 7 05 33 PM](https://user-images.githubusercontent.com/99847558/170807701-9c0a4d6f-450b-4854-8b7e-6f103eaed2b8.png)
![Screen Shot 2022-05-27 at 7 05 24 PM](https://user-images.githubusercontent.com/99847558/170807702-57ce2e84-b1ec-4d04-ad87-54c394708728.png)

2022-05-30 16:08 UTC, codingcodymiller requested changes

2022-05-30 16:08 UTC, codingcodymiller commented on javascript-loops/main.js
> +var keys = [];
This `keys` variable still needs to be moved inside the function block.

2022-06-10 06:21 UTC, louiewhitz commented
![Screen Shot 2022-06-
![Screen Shot 2022-06-09 at 11 09 26 PM](https://user-images.githubusercontent.com/99847558/173003256-7b3c3ee6-8983-423b-9f66-699dec0a9851.png)
09 at 11 16 36 PM](https://user-images.githubusercontent.com/99847558/173003219-2b81a357-6e32-4828-a1f7-2fb6ee53b19d.png)

2022-06-10 16:14 UTC, codingcodymiller approved these changes

2022-06-10 16:18 UTC, merged