JS and JSON
louiewhitz/c0522-code-solutions pull request #47
Opened 2022-05-27 21:34 UTC by louiewhitz

![Screen Shot 2022-05-27 at 2 32 02 PM](https://user-images.githubusercontent.com/99847558/170792066-c32b94ff-a1b0-4c3d-a050-1063680c58b2.png)

2022-05-30 16:00 UTC, codingcodymiller requested changes

2022-05-30 16:00 UTC, codingcodymiller commented on javascript-and-json/main.js
> +var newObj = '({"name":"Jason", "id":"456"})';
There shouldn't be any parentheses in this string

2022-06-10 06:13 UTC, louiewhitz commented
![Screen Shot 2022-06-09 at 11 09 26 PM](https://user-images.githubusercontent.com/99847558/173002075-05501f15-bfda-4a0d-9d06-aa444a57f628.png)

2022-06-10 16:18 UTC, codingcodymiller approved these changes

2022-08-13 20:00 UTC, merged