JS Local Storage
louiewhitz/c0522-code-solutions pull request #48
Opened 2022-05-27 23:30 UTC by louiewhitz

<img width="1177" alt="Screen Shot 2022-05-27 at 4 12 40 PM" src="https://user-images.githubusercontent.com/99847558/170800076-ca10de71-6620-44be-b8df-2763a3229bb0.png">

2022-05-30 15:56 UTC, codingcodymiller requested changes

2022-05-30 15:56 UTC, codingcodymiller commented on javascript-local-storage/data.js
> +  }
This should be happening when the page loads, not before it unloads.

2022-06-10 06:01 UTC, louiewhitz commented
![Screen Shot 2022-06-09 at 10 52 40 PM](https://user-images.githubusercontent.com/99847558/173000634-eec2d743-12bb-414f-bfa8-1ed26e6803a3.png)
![Screen Shot 2022-06-09 at 10 50 46 PM](https://user-images.githubusercontent.com/99847558/173000635-53b3509c-0ea0-4500-bcdf-5f819d42947c.png)

2022-06-10 16:19 UTC, codingcodymiller approved these changes

2022-08-12 19:15 UTC, merged